### ISSUE TITLE
[bug] sfpegFlowPathFlw - Button labels Not Appearing!

### ISSUE THREAD

**Issue by irfan2102** [pegros/PEG_FLW#10]
**Describe the bug**
I have configured the sfpegFlowPathFlw component and set the display mode to 'button'. For list of steps, I have used a stringified Json instead of flow active stages or a list of steps.

**To Reproduce**
1. Configure the component sfpegFlowPathFlw
2. set display mode to 'button'
3. Set List of Steps (JSON)

**Expected behavior**
Button labels displayed correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/fd94f26d-3410-4d66-a089-33b57bf6c4f0)
<img width="938" alt="image" src="https://github.com/user-attachments/assets/7fd8c222-0fa2-409c-a67b-efa8936e2196">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by pegros** [comment]
@irfan2102  This is not a bug but a lack of documentation on this use case.
Please specify the steps as `[{"label":"test1"},{"label":"test2","variant":"brand"}]` instead.

**Comment by pegros** [comment]
Component documentation has been updated.
