### ISSUE TITLE
[bug] sfpegFlowEmbed_CMP - OutputVar might be null in Helper

### ISSUE THREAD

**Issue by nicolas-despres** [pegros/PEG_FLW#8]
I have a case where I run a flow with no output vars. 
I have a crash on this line
https://github.com/pegros/PEG_FLW/blob/48f9069be24d8f67232f799c7fac8f132487040b/force-app/main/default/aura/sfpegFlowEmbed_CMP/sfpegFlowEmbed_CMPHelper.js#L115

Can we do something like ` let outputVar = event.getParam("outputVariables") || [];` to initialize the array? Or what is the required config I am missing? 
Thank you

**Comment by pegros** [comment]
Fixed in build [ffc460a](https://github.com/pegros/PEG_FLW/commit/ffc460a8f193403ba8271bb0f6fa3ba5ec04ef75)
