### ISSUE TITLE
[feat] All Components - Resize the tiles/fields when the component is rendered on non-desktop(PC) devices

### ISSUE THREAD

**Issue by pegros** [pegros/PEG_FLW#9]
**Is your feature request related to a problem? Please describe.**
If possible to render the fields display and cardTitle of the components on devices such as Mobile/Tablets and make them responsive.

**Describe the solution you'd like**
Responsive behaviour when on small screens to have all fields displayed on a single column.

**Describe alternatives you've considered**
Pull request #7  has been proposed 

**Additional context**
N/A

**Comment by pegros** [comment]
@bhavish030 I created a formal Issue for your contribution

**Comment by pegros** [comment]
As mentioned in my comment to pull request #7 I implemented the responsive behaviour in a different way, leveraging standard properties of the lightning-layout base component.
Now, the size configured is applied only in screens larger than tablet.
All components have been upgraded in commit [7ce01ff](https://github.com/pegros/PEG_FLW/commit/7ce01ff2c5d76b0329d68429f683439365be79dd)

**Comment by bhavish030** [comment]
Hello @pegros Thanks a lot for your help.
